name: cn-services-hermosa-ecs-autoscaling-request

on:
  pull_request:
    branches:
      - master
    paths:
    - 'modules/chownow/services/hermosa/ecs-autoscaling-request/**'

env:
  TF_VERSION: 0.14.7

defaults:
  run:
    working-directory: modules/chownow/services/hermosa/ecs-autoscaling-request

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Version
      id: version
      run: terraform version

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
